#! /bin/sh

# Flush everything when reloading the config files
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor settings
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Rules

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Calculator state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=offxce
bspc rule -a Celluloid state=floating
bspc rule -a MyNotes state=floating

# Other things to configure

bspc config focused_border_color "#005d96"

# Startup programs and scripts

~/.config/polybar/polybarlauch.sh
picom &
nitrogen --restore &
lxsession &

